[package]
name = "herald"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5.39", features = ["derive"] }
dhcproto = "0.13.0"
libc = "0.2.172"
socket2 = "0.5.10"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
